#!/usr/bin/env bash
# Using your debugging skills, find out whats keeping your Ubuntu containers
# Nginx installation from listening on port 80. Feel free to install whatever
# tool you need, start and destroy as many containers as you need to debug the
# issue. Then, write a Bash script with the minimum number of commands to
# automate your fix.

sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
sudo service nginx restart