#!/usr/bin/env bash
# This script changes the config without killing the worker processes
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
kill "$(pgrep 'nginx' | head -1)"
