#!/usr/bin/env bash
# This script display some values of /etc/passwd
while IFS=: read -r f1 f2 f3 f4 f5 f6 f7
do echo "$f1"":""$f3"":""$f6"
    f2=$f2
    f4=$f4
    f5=$f5
    f7=$f7
done < /etc/passwd