#!/usr/bin/env bash
# This script is displaying "Holberton School" 9 times and in the iteration 9 display "Hi"
i=1
while [ $i -le 11 ]
do
	if [ "$i" -eq 10 ]
	then
		echo "Hi"
		else
			echo "Best School"
			fi
        (( i++ ))
done